### ISSUE TITLE
Listado de índices y funciones

### ISSUE THREAD

**Issue by paocorrales** [AgRoMeteorologiaINTA/agromet#1]
### Lectura de datos

- [x] Lectura de archivo con formato NH
- [x] Lectura desde SIGA -> https://github.com/AgRoMeteorologiaINTA/siga

### Índices asociados a precipitación

- [x] Índice normalizado de precipitación (SPI)
- [x] Índice estandarizado de precipitación y evapotranspiración (SPEI)
- [x] Índice de severidad de sequía de Palmer
- [x] Índice autocalibrado de severidad de sequía de Palmer(sc-PDSI)
- [x] Cantidad de días secos
- [x] Deciles
- [x] Porcentaje de precipitación habitual: anomalía porcentual

### Índices asociados a temperatura

- [x] Índice de temperatura y humedad (ITH)
- [x] Heladas
- [x] Cantidad de dias con temp por encima de un umbral

### Funciones accesorias
- [x] Metadatos NH
- [x] Completar serie (con NAs)
- [x] Mapas disponibles como parte del paquete (Argentina, Argentina con provincias, paises limítrofes)
- [x] plot (mapa de Argentina con la pinta de INTA)
- [x] theme_inta

**Comment by eliocamp** [comment]
La descarga y lectura desde SIGA está en este paquete: https://github.com/AgRoMeteorologiaINTA/siga

**Comment by paocorrales** [comment]
@NatiGattinoni ¿Agregamos una función para calcular HR (en caso de que no estén los datos disponibles)? 

También se pueden usar las funciones de la parte de termodinámica de `metR`

**Comment by NatiGattinoni** [comment]
bien!! @paocorrales , se supone que ese dato se calcula cuando llegan los datos del SMN o de INTA y se completan en los NH y en la base del SIGA,  pero por alguna razón en algunos casos no aparece, así que si se puede calcular con las variables disponibles, perfecto. y también dar la opción de poder utilizar las funciones de metR
