### ISSUE TITLE
Mapas

### ISSUE THREAD

**Issue by paocorrales** [AgRoMeteorologiaINTA/agromet#10]
- [x] Sacar islas de Chile
- [x] Agregar mapa con departamentos
- [x] Ver si algunos se pueden reeemplazar por los de IGN

**Comment by yabellini** [comment]
- [ ] Chequear si tenemos mapas de ecoregiones de INTA.

**Comment by paocorrales** [comment]
@NatiGattinoni encontramos Argentina, las provincias y los departamentos en la pagina del IGN. No nos convence mucho porque el shape de Argentina incluye Antártida y tiene muchísima resolución. Eso hace que graficar sea un poco más lento. 

Por las dudas, todos los graficos del INTA usan los datos de acá? O hay algún otro repositorio oficial?https://www.ign.gob.ar/NuestrasActividades/InformacionGeoespacial/CapasSIG

Por otro lado no encontramos nada de paises limítrofes asi que por ahora queda la implementación con el paquete rnaturalearth.

**Comment by eliocamp** [comment]
Acá una preview de cómo funcionaría. `datos` tiene los datos de tmax y tmin para distintas estaciones del smn junto con su logitud y latitud. `mapear` (se puede elegir otro nombre) agarra lat lon y valor de los datos, hace kriging y grafica, agregando los países limítrofes y, opcionalmente, marcando la cordillera.

```
datos %>% 
  with(mapear(tmax, lon, lat, cordillera = TRUE,
              titulo = "Temperatura máxima", fuente = "Fuente: SMN"))

```

![image](https://user-images.githubusercontent.com/8617595/97815711-cad6ff00-1c6e-11eb-8652-323d2c153e10.png)

**Comment by NatiGattinoni** [comment]
@paocorrales le consulté a Aimé Espindola que es mi referente en mapas y me dijo que está perfecto que se bajen de ahí los shapes.  
Voy a ver si puede pasarme el shapes de países limítrofes para poder utilizarlo

**Comment by paocorrales** [comment]
Gracias Nati. Lo que falta resolver es el mapa de Argentina. La versión actual del IGN tiene mucha resolución, más de la que necesitamos para un gráfico como este e incluye Antartida. Eso hace que el gráfico tarde un par de dolorosos segundos en generarse. 

Mirando los términos y condiciones del IGN tengo la sospecha de que no podemos modificarlo para por ejemplo, simplificarlo un poco y que el gráficado sea más rápido. Por eso preguntaba si tal vez ustedes tienen alguna otra versión o si usan mapas de algún otro lugar.

**Comment by eliocamp** [comment]
Otro problema con estos datos que acabamos de notar es que por la enorme resolución del mapa, un plot simple, guardado en svg pesa 16Mb, que es una barbaridad y hace que sea imposible usar tests visuales (porque el peso del paquete va a ser demasiado grande para mandar a CRAN).

**Comment by yabellini** [comment]
Podriamos usar los de GeoINTA: Servicio WFS: http://geointa.inta.gov.ar/geoserver/wfs debería exisitr ahí un shape de Argentina con las provincias y sin la antartida.  GeoINTA es nuestra IDE oficial, asi que si usamos los mapas publicados ahi estamos usando cartografía oficial de INTA.

**Comment by eliocamp** [comment]
Ahí veo que hay varios mapitas de uso de suelo y cultivos, pero no encuentro que haya un shape file de los límites políticos. Estoy mirado acá: http://catalogo.geointa.inta.gob.ar/geonetwork/srv/eng/catalog.search#/search?facet.q=type%2Fdataset&resultType=details&fast=index&_content_type=json&from=1&to=20&sortBy=relevance

**Comment by NatiGattinoni** [comment]
Aquí les paso un shape con los paises límitrofes para que lo vean.. Este me lo había compartido Aimé en algún momento, voy a consultarle su procedencia.
[paiseslimitrofes.zip](https://github.com/AgRoMeteorologiaINTA/agromet/files/5507373/paiseslimitrofes.zip)

**Comment by NatiGattinoni** [comment]
probé esta función con el ejemplo que colocaron y con unos datos míos y en ambos casos sale este error: 
![image](https://user-images.githubusercontent.com/69041826/99089773-7dcb2500-25ac-11eb-95cb-f59d3789476e.png)

**Comment by eliocamp** [comment]
Gracias, ahí vemos ese error.

**Comment by eliocamp** [comment]
Creo que ya debería estar arreglado. Fijate actualizando el paquete y volviendo a intentar.

**Comment by NatiGattinoni** [comment]
perfecto!! 
por lo que veo, usa la paleta: scales::viridis_pal() pero también le puedo definir la que quiero usando esta función paleta_precipitacion(), es asi?

**Comment by eliocamp** [comment]
Tal cual. Eso abre la puerta para usar cualquier otra paleta que quieras. Van a estar también las otras paletas que pasaste que usás en surfer.

**Comment by paocorrales** [comment]
- [ ] Actualizar documentación de mapas con la fuente de los datos.
