### ISSUE TITLE
Reportes

### ISSUE THREAD

**Issue by eliocamp** [AgRoMeteorologiaINTA/agromet#11]
Algunos ejemplos

- http://climayagua.inta.gob.ar/sites/default/files/webform/infor_lunes/605_Evolucion_de_las_actuales_condiciones_climaticas%20(19deoctubrede2020).pdf 
- https://inta.gob.ar/sites/default/files/inta_registros_meteorologicos_anguil_2017.pdf 
- https://inta.gob.ar/sites/default/files/inta_registros_meteorologicos_anguil_2017.pdf 
https://inta.gob.ar/documentos/estadisticas-agroclimaticas-de-la-eea-anguil-ing-agr-guillermo-covas-periodo1973-2016 
- Este es un informe semanal: https://twitter.com/intaanguil/status/1237438448421736448?s=20 
- Este es un informe diario: https://twitter.com/intaanguil/status/1223309362397155329?s=20

**Comment by yabellini** [comment]
![imagen](https://user-images.githubusercontent.com/2473676/96774280-24604380-13bc-11eb-911a-cb81d16e5fcc.png)

**Comment by paocorrales** [comment]
Hola @yabellini, @NatiGattinoni! Comenzamos a trabajar en la plantilla de informes y nos vendría muy muy bien su feedback. 

Si instalan el paquete nuevamente ahora al generar un nuevo documento de RMarkdown -> From Template, deberían tener disponible un template `agromet_informe` y pueden así como sale knitearlo para ver que pinta tiene. 

El plan es que el ejemplo que aparece ahí tenga código que les sirva para arrancar algún informe. A menos que les parezca que con esos ejemplos es suficiente.

**Comment by yabellini** [comment]
No me aparece la plantilla

**Comment by paocorrales** [comment]
# Estilo del reporte

### Primera página

*Encabezado* 
- [ ] Logo de INTA a la izquierda
- [ ] Logo de Clima y Agua a la derecha (reemplazable por cualquier otro
- [ ] Nombre del informe corto + código de informe

*Cuerpo*
- [ ] Título largo
- [ ] Fecha
- [ ] Resumen

### Segunda página

*Encabezado*
- [ ] Vol y N° a la izquierda
- [ ] Fecha a la derecha

*Pie*
- [ ] Logo de INTA a la izquierda
- [ ] Número de página a la derecha

*Cuerpo* 
- [ ] Índice
- [ ] Contacto (mail)

### Páginas subsiguientes

- [ ] Mismo estilo que página 2
- [ ] Ejemplo de 2 figuras una al lado de la otra
- [ ] Ejemplo de tabla
- [ ] Título y textto
