### ISSUE TITLE
Función de graficado

### ISSUE THREAD

**Issue by paocorrales** [AgRoMeteorologiaINTA/agromet#12]
En vez de un método plot para cada función proponemos una función que reciba los datos y genere un mapa con la pinta de INTA (siguiendo más o menos el mapa que se ve acá)

![image](https://user-images.githubusercontent.com/9036871/97791140-dc0c0700-1bad-11eb-9e9a-65b49011251a.png)

**Comment by eliocamp** [comment]
Acá una preview de cómo funcionaría. `datos` tiene los datos de tmax y tmin para distintas estaciones del smn junto con su logitud y latitud. `mapear` (se puede elegir otro nombre) agarra lat lon y valor de los datos, hace kriging y grafica, agregando los países limítrofes y, opcionalmente, marcando la cordillera.

```
datos %>% 
  with(mapear(tmax, lon, lat, cordillera = TRUE,
              titulo = "Temperatura máxima", fuente = "Fuente: SMN"))

```

![image](https://user-images.githubusercontent.com/8617595/97815711-cad6ff00-1c6e-11eb-8652-323d2c153e10.png)

**Comment by NatiGattinoni** [comment]
genial!!
 fijensé, en Fuente poder poner SMN - INTA

la función kriging se selecciona con los parámetros por defecto?,  la función ya tiene asignada ese interpolado o podría elegirse otro, en el caso de utilizar alguna variable diferente a las tradicionales?

**Comment by paocorrales** [comment]
Nati, el título, subtítulo y caption se definen con argumentos de la funición `mapear()` así que podrías poner lo que quieras. En este caso Elio estaba probando con datos descargados del SMN y por eso puso "Fuente SMN".

No entendí tu pregunta sobre el kriging, te preferís a usar otros métodos de interpolación en vez de kriging? Si es así cuales usan?
