### ISSUE TITLE
Paletas de colores

### ISSUE THREAD

**Issue by paocorrales** [AgRoMeteorologiaINTA/agromet#14]
@yabellini @NatiGattinoni para que los gráficos tengan "pinta de" INTA sería genial tener las paletas de colores que usan normalmente y para que variables usan cada una.

Siempre se pueden agregar después, pero nos gustaría tener algunos ejemplos para probar y de paso dejar algo presentable :)

**Comment by yabellini** [comment]
Hay un manualmde identidad visual. Busco los colores y fuentes y lo pongo acá.

**Comment by eliocamp** [comment]
Si, encontramos el manual. Pero ahí no están las paletas de colores que usan para los gráficos.

**Comment by yabellini** [comment]
Pfff...ahí entendí.

**Comment by NatiGattinoni** [comment]
las escalas de los mapas las tengo en formato (no recuerdo la extensión) que se utiliza en Surfer. como se las podría pasar?
hay escala para precipitaciones, temperaturas y sus anomalías.

en un futuro esperaba modernizar los colores!!

**Comment by paocorrales** [comment]
Pasanos lo que tengas y vemos como leerlo y sumarlo al paquete, seguro que se puede!

Pero... también podemos aprovechar la oportunidad para definir nuevas paletas de colores :)

**Comment by yabellini** [comment]
Escala usada en Anguil PP:
- Menor a 10 mm RGB (209, 227, 31)
- Entre 11 y 20 mm RGB (78, 195, 106)
- Entre 21 y 30 mm RGB (32,147,140)
- Entre 31 y 40 mm RGB (72, 23, 105)
- Entre 41 y 50 mm RGB (172,3,94)
- Entre 51 y 60 mm RGB (218, 63, 245)
- Entre 60 y 70 mm RGB (173, 129, 252)
- Mayor a 70 mm RGB (141,172,255)

**Comment by eliocamp** [comment]
¿Así?

``` r
library(agromet)
set.seed(934)
datos_aleatorios <- data.frame(metadatos_nh(), pp = rgamma(nrow(metadatos_nh()), 1, scale = 20))


with(datos_aleatorios, mapear(pp, lon, lat, cordillera = TRUE,
                              breaks = breaks_precipitacion(),
                              paleta = paleta_precipitacion,
                              titulo = "Precipitación aleatoria", fuente = "Fuente: datos de ejemplo"))
```

![](https://i.imgur.com/VHVOjpY.png)

<sup>Created on 2020-11-08 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by NatiGattinoni** [comment]
Aquí les mando en el formato que les decía que usábamos en Surfer, quise pasárselas como hizo Yani pero me compliqué ...
[ESCALAS.zip](https://github.com/AgRoMeteorologiaINTA/agromet/files/5507371/ESCALAS.zip)

También suena interesante poder pensar nuevas propuestas.. a mi eso siempre me lleva mucho tiempo

**Comment by eliocamp** [comment]
Perfecto. Estamos agregando una función `leer_surfer()` que lee ese tipo de archivos en un formato para usar en `mapear()`
