### ISSUE TITLE
Documentación del paquete

### ISSUE THREAD

**Issue by paocorrales** [AgRoMeteorologiaINTA/agromet#16]
- [x] Metadatos
- [x] Licencia
- [x] Cómo contribuir en github
- [x] ¿Código de conducta? 
- [x] Readme en github
- [x] Documentación de cada función
- [x] Documentación de datos
- [x] Viñeta/s

**Comment by paocorrales** [comment]
**Preguntas para Yani/Nati**

- Incluimos un código de conducta en el repositorio? Si si, alguna propuesta o preferencia? Por defecto se usa el de Contributors Covenant y por suerte hay una traducción: https://www.contributor-covenant.org/translations/
- En la descripción del paquete se listas las personas involucradas y el rol. Por ahora estamos Elio (autor y manteiner - y aparece su mail para que le escriban o llegue informaición de CRAN si lo mandaramos-) y yo (autora) pero creo que deberíamos incluirlas con algún rol que consideren y definir quien queda como manteiner.

**Comment by yabellini** [comment]
Estoy de acuerdo con el código de conducta elegido (creo que la versión en
Español que está en T3 está de ese mismo CoC es un poquitito más inclusiva
con respecto del lenguaje).

Con respecto de licencia la estandar de MIT podría ser (no se si usamos
algo que nos obligue a otra licencia). Si no, me gusta también la licencia
hipocrática.

**Comment by paocorrales** [comment]
Genial, cambiamos a licencia MIT (la traducción esalió de wikipedia: https://es.wikipedia.org/wiki/Licencia_MIT porque no hay traducciones oficiales) y el código de conducta por ahora es la versión oficial porque no encontré ninguna versión en el repo de T3 (pero podemos modificar esto en el futuro).

**Comment by paocorrales** [comment]
**Licencia**

Bueno, revisé mejor la cuestión de la licencia teniendo en cuenta que estamos incluyendo código de un paquete. Inicialmente lo ibamos a incluir como dependencia pero encontramos un bug en el código que los autores no arreglan desde hace varios años. Esto nos obligó a copiar la parte del código que necesitamos para algunas funciones. Debido a esto no podemos usar una licencia con mayores libertades a las que usa ese paquete, tendríamos que al menos usar la misma (GPL -3). 

Además estas personas (los autores del código y tal vez la persona que aportó la corrección) pasan a ser copyright holders de este paquete. Eso quiere decir que en el caso de que se quiera cambiar la licencia hay que consultarles. 

Aguardo sus comentarios para hacer las modificaciones necesarias.

**Comment by yabellini** [comment]
Modifica nomas Pao a GLP-3.

Yani

**Comment by yabellini** [comment]
Aqui el link al CoC de T3, me parece que es una versión anterior a la que usaste para este repo.  Puedo verlo más tarde...no me acuerdo bien que parte no me gustaba mucho de la traducción al español original: https://teachtogether.tech/es/index.html#s:conduct

**Comment by yabellini** [comment]
Con respecto a autores y manteiners: @NatiGattinoni tenemos que charlar de esto.  Si lo vamos a mandar a CRAN!!!

**Comment by NatiGattinoni** [comment]
con respecto a este tema y dado mi desconocimiento, comparto lo que ustedes consideren más apropiado.
@yabellini mañana si tenes un ratito lo conversamos!!!

**Comment by eliocamp** [comment]
La viñeta ya está casi completa. El único problema es que para los ejemplos estamos usando los datos diarios del archivo NH0011.DAT que nos pasaste. ¿Tenemos permiso para ponerlo en el paquete y que esos datos sean públicos?

**Comment by yabellini** [comment]
Si el archivo contiene datos del SMN no se puede. Sólo con datos de INTA se podría.

**Comment by NatiGattinoni** [comment]
@eliocamp hace unos días les compartí un archivo zipeado con datos solo de estaciones de INTA, que si podemos incluir ya que son de acceso libre, lo comenté en la parte de lectura_NH.. avisame!
