### ISSUE TITLE
Revisión de funciones

### ISSUE THREAD

**Issue by paocorrales** [AgRoMeteorologiaINTA/agromet#17]
- [x] lectura_nh()
- [x] metadatos_nh()
- [x] decil() y anomalia_porcentual () [comparten documentación]
- [x] umbrales()
- [x] dias_promedio()
- [x] olas()
- [x] ith()
- [x] spi() y spei() [comparten documentación]
- [x] pdsi() y pdsi_ac() [comparten documentación]
- [x] completar_serie 
- [x] mapear()
- [x] mapa_argentina [y todos los mapas asociados]
- [x] escala_temp_min() [y el resto de las escalas]
- [x] leer_surfer()
- [ ] agromet_informe

**Comment by NatiGattinoni** [comment]
hola gente!!!! estaba usando la función decil() y mirando el ejemplo propuesto:

# Deciles mensuales
precip_mensual <- NH0358 %>%
  group_by(fecha = lubridate::floor_date(fecha)) %>%
  summarise(precip = mean(precip, na.rm = TRUE))

precip_mensual %>%
  mutate(deciles = decil(precip))


Se debería poner floor_date(fecha, "month") y en vez de mean(precip, na.rm = TRUE)) no debería ir sum()

**Comment by eliocamp** [comment]
Ahí está cambiado. :)
