### ISSUE TITLE
Release agromet 0.1.0

### ISSUE THREAD

**Issue by eliocamp** [AgRoMeteorologiaINTA/agromet#18]
Prepare for release: 
 
* [ ] Check that description is informative 
* [ ] Check licensing of included files 
* [x] `devtools::build_readme()` 
* [x] `usethis::use_cran_comments()` 
* [ ] `devtools::check(remote = TRUE, manual = TRUE)` 
* [ ] `devtools::check_win_devel()` 
* [ ] `rhub::check_for_cran()` 
* [ ] Update `cran-comments.md` 
 
Submit to CRAN: 
 
* [ ] `usethis::use_version('minor')` 
* [ ] `devtools::submit_cran()` 
* [ ] Approve email 
 
Wait for CRAN... 
 
* [ ] Accepted :tada: 
* [ ] `usethis::use_news_md()` 
* [ ] `usethis::use_github_release()` 
* [ ] `usethis::use_dev_version()` 
* [ ] Update install instructions in README 
* [ ] Tweet

**Comment by eliocamp** [comment]
Ejemplo de cran-comments.md

```
## Test environments

* local installation of elementary OS 5.1.7 Hera (Built on Ubuntu 18.04.4 LTS) R version 4.1.1

* winbuilder
  - R Under development (unstable) (2021-09-17 r80929)
  - Ubuntu Linux 20.04.1 LTS, R-release, GCC


* rhub
  - Windows Server 2008 R2 SP1, R-devel, 32/64 bit


## R CMD check results

0 errors | 0 warnings | 1 notes 

I get these notes that seem like false positives, since I can browse to those
URLs with no problems.


Found the following (possibly) invalid URLs:
  URL: https://doi.org/10.1175/1520-0469(1985)042<0217:OTTDPO>2.0.CO;2
    From: man/EPflux.Rd
    Status: 403
    Message: Forbidden
  URL: https://doi.org/10.1175/1520-0469(2001)058<0608:AFOAPI>2.0.CO;2
    From: man/WaveFlux.Rd
    Status: 403
    Message: Forbidden

```

**Comment by yabellini** [comment]
Cerrando esto porque el envio a CRAN se hará después que el paquete pase por la revisión de rOpenSci.
