### ISSUE TITLE
scPDSI ya no está en CRAN

### ISSUE THREAD

**Issue by paocorrales** [AgRoMeteorologiaINTA/agromet#19]
Bajaron el paquete porque no resolvieron algunos problemas. Ahora este paquete está como dependencia de agromet. Si queremos mandar esto a CRAN vamos a tener que resolver como hacemos para esquivar este paquete.

**Comment by yabellini** [comment]
Ups...lo usabamos para calcular algún índice? Podríamos generar el cálculo nosotros?

**Comment by eliocamp** [comment]
Se usa para el índice de Palmer. Se basa en un modelo de balance de humedad que en el paquete scPDSI está en C++ y me da la impresión de que correrlo en R sería muy lento.

**Comment by eliocamp** [comment]
Pregunté en el github del paquete a ver qué onda. https://github.com/Sibada/scPDSI/issues/4
Sino, vemos si podemos forkear y arreglarlo nosotres.

**Comment by eliocamp** [comment]
Agregué las rutinas de C y todo eso a nuestro paquete y anda. @yabellini , ¿sabés cómo hay que hacer para dar crédito a les autores del otro paquete?

**Comment by yabellini** [comment]
Buena pregunta. Esto como mínimo creo. Voy a consultar en algunos foros a ver que recomiendan.

**Comment by yabellini** [comment]
Comentarios que me dejaron luego de la consulta: 

Some resources:
https://r-pkgs.org/license.html#code-you-bundle :sparkles: is quite fitting for your use case. Licensing stuff as well as "how to include" (which covers giving credit) is discussed.

I also looked through the archive on R-package-devel to see relevant convos but this is less useful I think (apart from seeing this is a recurring challenge
https://www.mail-archive.com/r-package-devel@r-project.org/msg03609.html you are doing solution 1 i.e. "vendoring".
https://stat.ethz.ch/pipermail/r-package-devel/2021q2/007026.html which tells you should "check" but sadly not know how/where.

Lastly, have you checked whether the author watched their own GitHub repo? It might be worth emailing them (or simply tagging them in an issue, if you see they don't watch the repo but are active in other repos)?

**Comment by eliocamp** [comment]
Leyendo r-packages lo que tendríamos que hacer es agregar la información de la licencia en el archivo donde está el código que copiamos y agregar al autor del paquete como "copyright holder" en el DESCRIPTION. 

Igual antes de eso podríamos tratar de contactar a Sibaba por otros medios; no parece que tenga mucha actividad en github. 

![](https://i.imgur.com/PrBJwuN.png)

**Comment by yabellini** [comment]
Me parece bien lo que propones de intentar contactarlo antes, no se me ocurre como.

**Comment by eliocamp** [comment]
Le voy a mandar un mail a la dirección que está en el DESCRIPTION: https://github.com/Sibada/scPDSI/blob/master/DESCRIPTION

**Comment by eliocamp** [comment]
No recibí respuesta, así que ya fue. Agregué al autor como copyright holder (de paso también al del spi).

**Comment by yabellini** [comment]
Perfecto Elio!!

**Comment by eliocamp** [comment]
Ya estaría en condiciones de mandar a CRAN.

**Comment by yabellini** [comment]
Hay que genial.  Ahora nos ponemos de acuerdo en un día de esta semana asi lo hacemos :-)
