### ISSUE TITLE
INFORME AGROMET - RMD

### ISSUE THREAD

**Issue by NatiGattinoni** [AgRoMeteorologiaINTA/agromet#26]
Quise generar el Rmd directamente con el ejemplo puesto en el paquete.
Una vez que me indica: _output file: probando.knit.md_ , aparece una ventana emergente indicando que _inserte un disco_, luego de indicarle reintentar, comienza una serie de mensajes y finalmente me indica lo siguiente: 
![error_informe_agromet](https://user-images.githubusercontent.com/69041826/138617353-21e54178-9c98-42aa-b9d5-c06cfb992887.JPG)

no tuve tiempo en meterme al link que sugiere. Pero mientras pruebo, dejo este comentario por acá.
Gracias!!!!

**Comment by paocorrales** [comment]
@NatiGattinoni este sigue siendo un error o ahora podés generar los informes?

**Comment by NatiGattinoni** [comment]
@paocorrales Retomo este tema, instalé todo desde cero en una compu nueva (win10). Comencé a generar un informe y el **primer mensaje fue que no encontraba "xelatex".
Procedí a correr tinytex::install_tinytex() y ese mensaje desapareció.**

Ahora parece **como si se hubiese tindado en alguna acción**:
![image](https://github.com/AgRoMeteorologiaINTA/agromet/assets/69041826/7e98b1eb-96c1-4a76-a105-65e2eb21dd41)

y hasta ahi puede llegar

**Comment by paocorrales** [comment]
Hola Nati, 

Al ser una instalación de R nueva, te vas a encontrar con cosas que necesitas instalar. En este caso, como el informe se genera en pdf te pide que tenes LaTex. La mejor manera de hacerlo es con tinytex como hiciste y si bien esa parte puede ser rápida, es posibleque luego al intentar generar el informe se instalen paquetes de latex extra.

Esto puede demorar un poco, si aún no lograste que knitee, probaría de nuevo!

**Comment by NatiGattinoni** [comment]
hola Pao!
como has dicho, dejé que termine su proceso para el cual tomó un tiempito, pero finalmente generó el informe. Luego probé generar otro y en esta oportunidad lo hice casi inmediatamente.
