### ISSUE TITLE
Lectura de NH

### ISSUE THREAD

**Issue by paocorrales** [AgRoMeteorologiaINTA/agromet#3]
ToDo list para lectura_nh()

- [x] Documentar unidades de cada variable
- [x] Revisar `data$viento_med <- round(data$viento_med*5/18, digits = 1)`
- [x] Agregar  códigos OMM en los metadatos?
- [x] Que devuelva un data frame en vez de un data table
- [x] Tal vez metadatos_nh() puede hacer un filtro para devolver las estaciones según el código o según la región
- [x] Vectorizar la función para que reciba una lista de archivos

**Comment by paocorrales** [comment]
Elimino` data$viento_med <- round(data$viento_med*5/18, digits = 1)`

Cuando revisemos unidades de cada variable vemos si es necesario hacer alguna conversión.

**Comment by paocorrales** [comment]
`metadatos_nh` ahora puede filtrar por código de estación o por latitud y/o longitud. 

`metadatos_nh(codigo = "0001)`
`metadatos_nh(lat = c(-35, -25), lon = c(-65, -55)) `

Pero además tiene un método de graficado rápido!!!

`plot(metadatos_nh()`

**Comment by paocorrales** [comment]
@NatiGattinoni para terminar estas funciones nos faltaría:

- [ ] unidades de las variables
- [ ] limpieza de nombres de las estaciones y una nueva columna para identificar la institución de origen

**Comment by NatiGattinoni** [comment]
UNIDADES DE LAS VARIABLES:
 TMAX  TMIN  PRECIP TMIN5 HELIOF HEREL  TVAP   HR  Td  VV10   VV2      RG   ETP
      ºC     ºC       mm     ºC            hs        %       hPa     %   ºC   km/h  km/h   MJ/m2  mm

HELIOF: HELIOFANIA EFECTIVA
HEREL: HELIOFANIA RELATIVA
TVAP: TENSION DE VAPOR
VV10 Y VV2:  VIENTO A 10 Y 2 M (desde el SMN viene el dato a 10m y se estima el datos a 2m con un factor de conversión, bastante aproximado: 0.8 )

Quizas hayan visto que por ejemplo en el SIGA también figura la presión, la profundidad de la napa y la radiación neta, que eran variables que no estaban consideradas cuando se armaron en un principio los archivos NH

**Comment by NatiGattinoni** [comment]
En cuanto a la limpieza del listado de nombres: armé este archivo, me falta completar la columna de provincia pero quería enviárselos para que lo vean..
[LISTADO_SMN-INTA.zip](https://github.com/AgRoMeteorologiaINTA/agromet/files/5475849/LISTADO_SMN-INTA.zip)

**Comment by paocorrales** [comment]
Está perfecto Nati, lo importante es que tenga la información que vos necesites para trabajar!

**Comment by eliocamp** [comment]
@NatiGattinoni Para testear la función de lectura de datos NH vamos a tener que agregar al menos una parte de algunos datos en el repositorio, ¿te parece bien? Si preferís que no estén, podríamos modificar los datos agergándole datos aleatorios.

**Comment by NatiGattinoni** [comment]
@eliocamp no llegué a contestarte y avanzaron con el tema de datos aleatorios (cero que lo vi en el mapa)?. 
Cuando decis una parte, es que incluirán en el repositorio algunos archivos NH? si es asi te mando los de algunas estaciones de INTA, que considero más apropiado.

[NH_INTA.zip](https://github.com/AgRoMeteorologiaINTA/agromet/files/5507398/NH_INTA.zip)

**Comment by NatiGattinoni** [comment]
estoy probando esta función.

* tuve un warning en lo que es fecha, completa con NA hasta aprox 1990.. lo probé en dos archivos. 

![image](https://user-images.githubusercontent.com/69041826/98555946-49402c00-2281-11eb-9e08-73b9146c7f24.png)


* en el nombre de columna donde dice t_aire_max.. debe ir tmin_intemperie_5cm... o algo parecido ya que allí se coloca el valor de la temperatura mínima diaria a intemperie  a los 5cm del suelo.
![image](https://user-images.githubusercontent.com/69041826/98556182-89071380-2281-11eb-937e-d7c5329d9fb5.png)

**Comment by paocorrales** [comment]
Hola Nati! 

Sobre tu primer pregunta, los warnings aparecen cuando el archivo tiene problemas, es posible que no tenga exactamente el mismo formato que el resto. ¿Me lo mandas así lo miro? Tal vez hay algo que podamos hacerle a la función para que tenga en cuenta estas diferencias. 

Sobre el otro comentario, pusimos esos nombres en las columnas porque son los que estaban en tu script. Si querés que tengan nombres distintos avisame como deberían aparecer exactamente y lo cambiamos. Si podés también revisa la documentación de esta función así cambiamos ahí todo lo que consideres.

**Comment by paocorrales** [comment]
Update!! Tenía el archivo de esa estación en un zip que nos compartiste hace unos días. El problema es que las fechas no están exactamente igual en todos los archivos, algunos usan 2020 1 1, y otros 20200101. Pero ya está arreglado, si volver a instalar el paquete ahora no deberias tener problemas.

**Comment by NatiGattinoni** [comment]
> @NatiGattinoni para terminar estas funciones nos faltaría:
> 
> * [x]  unidades de las variables
> * [ ]  limpieza de nombres de las estaciones y una nueva columna para identificar la institución de origen

Pao, aquí les envío le listado de estaciones en donde agregué una columna con la provincia y la institución de origen. 
¿Este archivo puede ser modificado en algún otro momento, por ejemplo si es que se cambia algún número de identificación
[LISTADO_SMN-INTA.zip](https://github.com/AgRoMeteorologiaINTA/agromet/files/5559772/LISTADO_SMN-INTA.zip)
?
