### ISSUE TITLE
PROPUESTAS DE NUEVAS FUNCIONES

### ISSUE THREAD

**Issue by NatiGattinoni** [AgRoMeteorologiaINTA/agromet#36]
Aquí pueden dejarnos sus propuestas de funciones que consideren apropiadas sumar al paquete. De esta manera podremos ir analizando la posibilidad de incluirlas. muchas gracias

**Comment by yabellini** [comment]
Hola @NatiGattinoni ! Que bueno que estés pidiendo nuevas ideas de funciones.  

Para que podamos trabajarlas adecuadamente es mejor que cada una sea un issue diferente.  De esta manera se pueden priorizar, asignar a la persona mas adecuada para resolverla, discutirla con foco en ese problema/funcionalidad nueva (sin mezclar diferentes pedidos) y cerrarla cuando se termine. 

Recomiendo que si alguien quiere contribuir lea la guía de contribución de este paquete y que está en este repo: https://github.com/AgRoMeteorologiaINTA/agromet/blob/master/.github/CONTRIBUTING.md

En resumen la regla general es:

- Antes de crear un issue revisar los que están abiertos a ver si lo que necesutan ya está en proceso, comentar en ese si es así.
- Si lo que quieren NO está en un issue entonces abrir uno nuevo. 

Espero que esto sirva!

Mi recomendación es también cerrar este issue para que no confunda.

**Comment by NatiGattinoni** [comment]
Hola @yabellini perfecto, lo armé como inexperta todavía en este tipo de trabajos. 
sigo tus recomendaciones para un buen trabajo e intercambio y esto que vos indicas se lo haré llegar al grupo.
muchas gracias!

**Comment by yabellini** [comment]
Es lo lindo de esto Nati, que podemos ir aprendiendo juntos :-) Gracias!!!
