### ISSUE TITLE
SPI

### ISSUE THREAD

**Issue by eliocamp** [AgRoMeteorologiaINTA/agromet#4]
La función para calcular el SPI está acá: https://github.com/AgRoMeteorologiaINTA/agromet/blob/master/R/spi.R

Pregunta para @NatiGattinoni: ¿el SPI se calcula para cada mes por separado para eliminar el ciclo anual?

Probando con datos simulados me da esto:

```r
library(magrittr)
library(ggplot2)

pp2 <- data.frame(fecha = seq(as.Date("1985-01-01"), 
                              as.Date("2015-12-01"), 
                              by = "1 month"))
set.seed(42)    # ¡reproducible!
# Simula datos de precipitación con una distribución gamma con un siclo anual en 
# el parámetro de forma
pp2$pp <- rgamma(nrow(pp2), shape = 1, scale = 10*(cos((lubridate::month(pp2$fecha) - 1)/11*pi*2) + 1))


pp2 %>% 
  dplyr::summarise(spi(fecha, pp, 1:24)) %>% 
  ggplot(aes(fecha, escala)) +
  geom_contour_filled(aes(z = spi, fill = ..level_mid..)) +
  scale_fill_gradient2(limits = c(-2, 2), oob = scales::squish) 
```

![image](https://user-images.githubusercontent.com/8617595/95690180-22dc9180-0bec-11eb-92a4-1996659d3180.png)

¿Es razonable que de desvíos tan grandes?

**Comment by eliocamp** [comment]
Perfecto, entonces. Vímos que estabas usando el paquee SPEI y es lo que usamos para la función. 

Rellenar los datos es todo un tema, especialmente para precipitación. No creo que ningún método sea demasiado bueno. En especial para precipitacion!

**Comment by paocorrales** [comment]
Todo list para SPI y SPEI

- [ ] Wrap para SPEI cambiando distribución
- [ ] Método plot

**Comment by eliocamp** [comment]
[ ] Permitir usar datos de referencia. 

Tratando de hacer eso encontré que hay un bug en {SPEI} cuando uno trata de pasarle los parámetros de las distribuciones en vez de que haga el fit con los datos. Ya envíé un mail al mantainer, pero si no responde y no arregla (el paquete no se actualiza desde 2017), quizás va a haber que programar la función propia.

**Comment by eliocamp** [comment]
Actualización: El error fue reportado en el github hace 2 años y no hay noticia. La veo mal. https://github.com/sbegueria/SPEI/issues/16

**Comment by paocorrales** [comment]
Estamos usando de base elcódigo del paquete SPI pero arreglando el bug que tenía. 

- [ ] Revisar licencia y como citar correctamente el uso del código de SPI

**Comment by paocorrales** [comment]
@NatiGattinoni cuando sepas avisanos que calculo de SPI hacen más frecuentemente y que visualización usan así armamos el método plot asociado a la función.

**Comment by eliocamp** [comment]
El SPI ahora devuelve una serie completa (con NAs explícitos en donde en los datos de entrada hay NAs implícitos). Quizás debería devolver el SPI para las fechas de entrada nomás.

**Comment by eliocamp** [comment]
No, mejor que devuelva la serie completa; con datos faltnates explícitos. 

Expandí la nota de la procedencia del código de SPI y la licencia (GPL).

**Comment by NatiGattinoni** [comment]
> @NatiGattinoni cuando sepas avisanos que calculo de SPI hacen más frecuentemente y que visualización usan así armamos el método plot asociado a la función.

@paocorrales lo usaremos a nivel país, con los valores de SPI para una escala, por ejemplo SPI-3. y fijamos el mes. luego también se puede visualizar la evolución temporal seleccionando algunas estación, podría pensarse en usar el gráfico que colocó Elio mas arriba.

buen, creo que no fui muy precisa jaja.. pero ese sería el orden del uso de la información de SPI. Con lo cual, se fija un mes, una escala del spi y se puede visualizar a nivel de mapa o evolución temporal a través de los años.

**Comment by NatiGattinoni** [comment]
estaba probando esta función
DISCULPEN que haga esta consulta!!!, pero me perdí en como utilizarla.
debo ingresar los datos diarios o mensuales de lluvia? puedo tener un archivo que tenga las columnas fechas, prcp.. que lo obtengo de la función lectura_NH? (no lo pude probar porque no me lee la fecha correctamente..

**Comment by paocorrales** [comment]
Buenas! Según lo que entendemos el SPI se calcula para datos mensuales, así que tendrías que calcular primero los valores mensuales de precipitación a partir de los datos diarios. En la documentación hay un ejemplo con datos aleatorios pero si querés probar con datos de NH y asumiendo que tenés el archivo NH0011.DAT en la carpeta datos, debería ser algo así:

``` r
library(agromet)
library(dplyr)
library(lubridate)


obs <- leer_nh("datos/NH0011.DAT")
#> Warning: 1 parsing failure.
#>   row col expected actual                                      file
#> 20969 etp  3 chars      3 '/home/pao/INTA/agromet/datos/NH0011.DAT'

obs %>% 
  group_by(fecha = floor_date(fecha, "month")) %>% 
  summarise(pp_mensual = sum(precip)) %>% 
  summarise(spi(fecha, pp_mensual, escalas = 3))
#> `summarise()` ungrouping output (override with `.groups` argument)
#> # A tibble: 773 x 3
#>    fecha               escala     spi
#>    <dttm>               <dbl>   <dbl>
#>  1 1956-04-01 00:00:00      3 NA     
#>  2 1956-05-01 00:00:00      3 NA     
#>  3 1956-06-01 00:00:00      3  1.42  
#>  4 1956-07-01 00:00:00      3  0.0749
#>  5 1956-08-01 00:00:00      3  1.88  
#>  6 1956-09-01 00:00:00      3  1.57  
#>  7 1956-10-01 00:00:00      3  2.16  
#>  8 1956-11-01 00:00:00      3 NA     
#>  9 1956-12-01 00:00:00      3 NA     
#> 10 1957-01-01 00:00:00      3 NA     
#> # … with 763 more rows
```

Si querés hacerlo para todas las estaciones, entonces deberías leer todas las estaciones juntas y agrupar también por estación. En la documentación también hay algún detalle sobre el periodo de referencia a utilizar.

**Comment by NatiGattinoni** [comment]
Buenas! corrió perfecto Pao! 
estoy probando lo de la función spi_referencia(), para poder entenderla.....para poder utilizarla debo armar otro DF? o podría, y eso no se como hacerlo: decirle que del archivo de datos mensuales (que uso para calcular el spi) seleccione fecha y precip desde 1961 -2010.. ?

**Comment by NatiGattinoni** [comment]
no recuerdo cómo se resolvió el tema del gráfico....

**Comment by eliocamp** [comment]
> Buenas! corrió perfecto Pao!
> estoy probando lo de la función spi_referencia(), para poder entenderla.....para poder utilizarla debo armar otro DF? o podría, y eso no se como hacerlo: decirle que del archivo de datos mensuales (que uso para calcular el spi) seleccione fecha y precip desde 1961 -2010.. ?

Estuvimos pensando y decidimos cambiar un poco cómo se hace. Cuando actualices el paquete ahora la forma recomendada es usando un vector lógico. Entonces, si tus observaciones están en `obs` y querés usar como referencia los datos anteriores a 1979, harías algo como esto: 

```r
obs %>% 
  group_by(estacion) %>%
  summarise(spi(fecha, pp_mensual, escalas = 3, referencia = lubridate::year(fecha) <= 1979))
```
