### ISSUE TITLE
Palmer

### ISSUE THREAD

**Issue by paocorrales** [AgRoMeteorologiaINTA/agromet#8]
En principio requiere la capacidad de carga, que por defecto es 100 mm, pero hay que revisar bien la bibliografía para asegurarnos de estar entendiendo bien ese argumento.

**Comment by NatiGattinoni** [comment]
por lo que estuve mirando el parámetro que se necesita para caracterizar la parte de disponibilidad de agua en el suelo es el agua útil, calculada a partir de la diferencia entre la capacidad de campo (CC) y el punto de marchitez (PMP). Si bien está fijo por defecto, se le puede indicar que asigne una valor según la localidad? o por ejemplo que capture el valor desde otro archivo, ya que también podría obtenerse desde el resultado del balance hidrológico de la FAUBA-SMN-INTA?????

**Comment by eliocamp** [comment]
El valor es un argumetno de la función, así que le podés pasar el número que querias.
